/*
insert license info here
*/
using System;

namespace dcl.entity
{
    /// <summary>
    ///	Generated by MyGeneration using the IBatis Object Mapping template
    /// </summary>
    [Serializable]
    public sealed class BarcodePatients
    {
        #region Private Members
        private bool _isChanged;
        private bool _isDeleted;
        private Int64 _id;
        private string _number;
        private string _code;
        private int _frequency;
        private string _typeid;
        private string _typename;
        private string _bednumber;
        private string _name;
        private string _sex;
        private string _age;
        private string _deptcode;
        private string _deptname;
        private string _diag;
        private string _doctorcode;
        private string _doctname;
        private string _hisname;
        private string _sampleid;
        private string _samplename;
        private DateTime _date;
        private float _times;
        private int _printflag;
        private DateTime _printdate;
        private string _printercode;
        private string _printername;
        private string _cuvcode;
        private string _cuvname;
        private float _mincollectsum;
        private string _mincollectunit;
        private bool _urgentflag;
        private string _ctype;
        private string _originid;
        private string _originname;
        private int _receiverflag;
        private DateTime _receiverdate;
        private string _receivercode;
        private string _receivername;
        private int _bloodflag;
        private DateTime _blooddate;
        private string _bloodcode;
        private string _bloodname;
        private int _sendflag;
        private DateTime _senddate;
        private string _sendcode;
        private string _sendname;
        private int _reachflag;
        private DateTime _reachdate;
        private string _reachcode;
        private string _reachname;
        private string _expression;
        private string _computer;
        private string _socialnumber;
        private string _empid;
        private string _info;
        private string _hospitalid;
        private int _barcodetype;
        private string _status;
        private string _statuscname;
        private string _deleteflag;
        private DateTime _birthday;
        private bool _blood;
        private DateTime _orderTime;
        private string _sampleRemarkid;
        private string _sampleRemarkName;
        private int _returnFlag;
        private int _returnTimes;
        private DateTime _lastActionTime;
        private string _bc_pid;
        private string _bcAppId;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public BarcodePatients()
        {
            _id = 0;
            _number = null;
            _code = null;
            _frequency = 0;
            _typeid = null;
            _typename = null;
            _bednumber = null;
            _name = null;
            _sex = null;
            _age = null;
            _deptcode = null;
            _deptname = null;
            _diag = null;
            _doctorcode = null;
            _doctname = null;
            _hisname = null;
            _sampleid = null;
            _samplename = null;
            _date = new DateTime();
            _times = 0;
            _printflag = 0;
            _printdate = new DateTime();
            _printercode = null;
            _printername = null;
            _cuvcode = null;
            _cuvname = null;
            _mincollectsum = 0;
            _mincollectunit = null;
            _urgentflag = false;
            _ctype = null;
            _originid = null;
            _originname = null;
            _receiverflag = 0;
            _receiverdate = new DateTime();
            _receivercode = null;
            _receivername = null;
            _bloodflag = 0;
            _blooddate = new DateTime();
            _bloodcode = null;
            _bloodname = null;
            _sendflag = 0;
            _senddate = new DateTime();
            _sendcode = null;
            _sendname = null;
            _reachflag = 0;
            _reachdate = new DateTime();
            _reachcode = null;
            _reachname = null;
            _expression = null;
            _computer = null;
            _socialnumber = null;
            _empid = null;
            _info = null;
            _hospitalid = null;
            _barcodetype = 0;
            _status = null;
            _statuscname = null;
            _deleteflag = null;
            _birthday = new DateTime();
            _blood = false;
            _orderTime = new DateTime();
            _sampleRemarkid = null;
            _sampleRemarkName = null;
            _returnFlag = 0;
            _returnTimes = 0;
            _lastActionTime = new DateTime();
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>		
        public Int64 Id
        {
            get { return _id; }
            set { _isChanged |= (_id != value); _id = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string PID
        {
            get { return _bc_pid; }
            set { _isChanged |= (_bc_pid != value); _bc_pid = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Number
        {
            get { return _number; }
            set
            {


                _isChanged |= (_number != value); _number = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Code
        {
            get { return _code; }
            set
            {

                _isChanged |= (_code != value); _code = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public int Frequency
        {
            get { return _frequency; }
            set { _isChanged |= (_frequency != value); _frequency = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Typeid
        {
            get { return _typeid; }
            set
            {

                _isChanged |= (_typeid != value); _typeid = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string TypeName
        {
            get { return _typename; }
            set
            {


                _isChanged |= (_typename != value); _typename = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string BedNumber
        {
            get { return _bednumber; }
            set
            {


                _isChanged |= (_bednumber != value); _bednumber = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Name
        {
            get { return _name; }
            set
            {

                _isChanged |= (_name != value); _name = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Sex
        {
            get { return _sex; }
            set
            {

                _isChanged |= (_sex != value); _sex = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Age
        {
            get { return _age; }
            set
            {

                _isChanged |= (_age != value); _age = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string DeptCode
        {
            get { return _deptcode; }
            set
            {

                _isChanged |= (_deptcode != value); _deptcode = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string DeptName
        {
            get { return _deptname; }
            set
            {

                _isChanged |= (_deptname != value); _deptname = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Diag
        {
            get { return _diag; }
            set
            {

                _isChanged |= (_diag != value); _diag = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string DoctorCode
        {
            get { return _doctorcode; }
            set
            {

                _isChanged |= (_doctorcode != value); _doctorcode = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string DoctName
        {
            get { return _doctname; }
            set
            {

                _isChanged |= (_doctname != value); _doctname = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string HisName
        {
            get { return _hisname; }
            set
            {

                _isChanged |= (_hisname != value); _hisname = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Sampleid
        {
            get { return _sampleid; }
            set
            {

                _isChanged |= (_sampleid != value); _sampleid = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string SampleName
        {
            get { return _samplename; }
            set
            {

                _isChanged |= (_samplename != value); _samplename = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime Date
        {
            get { return _date; }
            set { _isChanged |= (_date != value); _date = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public float Times
        {
            get { return _times; }
            set { _isChanged |= (_times != value); _times = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public int PrintFlag
        {
            get { return _printflag; }
            set { _isChanged |= (_printflag != value); _printflag = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime PrintDate
        {
            get { return _printdate; }
            set { _isChanged |= (_printdate != value); _printdate = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string PrinterCode
        {
            get { return _printercode; }
            set
            {

                _isChanged |= (_printercode != value); _printercode = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string PrinterName
        {
            get { return _printername; }
            set
            {

                _isChanged |= (_printername != value); _printername = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string CuvCode
        {
            get { return _cuvcode; }
            set
            {

                _isChanged |= (_cuvcode != value); _cuvcode = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string CuvName
        {
            get { return _cuvname; }
            set
            {

                _isChanged |= (_cuvname != value); _cuvname = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public float MinCollectSum
        {
            get { return _mincollectsum; }
            set { _isChanged |= (_mincollectsum != value); _mincollectsum = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string MinCollectUnit
        {
            get { return _mincollectunit; }
            set
            {

                _isChanged |= (_mincollectunit != value); _mincollectunit = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public bool UrgentFlag
        {
            get { return _urgentflag; }
            set { _isChanged |= (_urgentflag != value); _urgentflag = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Ctype
        {
            get { return _ctype; }
            set
            {

                _isChanged |= (_ctype != value); _ctype = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Originid
        {
            get { return _originid; }
            set
            {

                _isChanged |= (_originid != value); _originid = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string OriginName
        {
            get { return _originname; }
            set
            {

                _isChanged |= (_originname != value); _originname = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public int ReceiverFlag
        {
            get { return _receiverflag; }
            set { _isChanged |= (_receiverflag != value); _receiverflag = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime ReceiverDate
        {
            get { return _receiverdate; }
            set { _isChanged |= (_receiverdate != value); _receiverdate = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string ReceiverCode
        {
            get { return _receivercode; }
            set
            {

                _isChanged |= (_receivercode != value); _receivercode = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string ReceiverName
        {
            get { return _receivername; }
            set
            {

                _isChanged |= (_receivername != value); _receivername = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public int BloodFlag
        {
            get { return _bloodflag; }
            set { _isChanged |= (_bloodflag != value); _bloodflag = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime BloodDate
        {
            get { return _blooddate; }
            set { _isChanged |= (_blooddate != value); _blooddate = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string BloodCode
        {
            get { return _bloodcode; }
            set
            {

                _isChanged |= (_bloodcode != value); _bloodcode = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string BloodName
        {
            get { return _bloodname; }
            set
            {

                _isChanged |= (_bloodname != value); _bloodname = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public int SendFlag
        {
            get { return _sendflag; }
            set { _isChanged |= (_sendflag != value); _sendflag = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime SendDate
        {
            get { return _senddate; }
            set { _isChanged |= (_senddate != value); _senddate = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string SendCode
        {
            get { return _sendcode; }
            set
            {

                _isChanged |= (_sendcode != value); _sendcode = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string SendName
        {
            get { return _sendname; }
            set
            {

                _isChanged |= (_sendname != value); _sendname = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public int ReachFlag
        {
            get { return _reachflag; }
            set { _isChanged |= (_reachflag != value); _reachflag = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime ReachDate
        {
            get { return _reachdate; }
            set { _isChanged |= (_reachdate != value); _reachdate = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string ReachCode
        {
            get { return _reachcode; }
            set
            {

                _isChanged |= (_reachcode != value); _reachcode = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string ReachName
        {
            get { return _reachname; }
            set
            {

                _isChanged |= (_reachname != value); _reachname = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Expression
        {
            get { return _expression; }
            set
            {

                _isChanged |= (_expression != value); _expression = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Computer
        {
            get { return _computer; }
            set
            {

                _isChanged |= (_computer != value); _computer = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string SocialNumber
        {
            get { return _socialnumber; }
            set
            {

                _isChanged |= (_socialnumber != value); _socialnumber = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Empid
        {
            get { return _empid; }
            set
            {

                _isChanged |= (_empid != value); _empid = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Info
        {
            get { return _info; }
            set
            {

                _isChanged |= (_info != value); _info = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Hospitalid
        {
            get { return _hospitalid; }
            set
            {

                _isChanged |= (_hospitalid != value); _hospitalid = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public int BarcodeType
        {
            get { return _barcodetype; }
            set { _isChanged |= (_barcodetype != value); _barcodetype = value; }
        }

        public int ReturnFlag
        {
            get { return _returnFlag; }
            set { _isChanged |= (_returnFlag != value); _returnFlag = value; }
        }

        public int ReturnTimes
        {
            get { return _returnTimes; }
            set { _isChanged |= (_returnTimes != value); _returnTimes = value; }
        }

        public DateTime LastActionTime
        {
            get { return _lastActionTime; }
            set { _isChanged |= (_lastActionTime != value); _lastActionTime = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Status
        {
            get { return _status; }
            set
            {

                _isChanged |= (_status != value); _status = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string StatusCname
        {
            get { return _statuscname; }
            set
            {

                _isChanged |= (_statuscname != value); _statuscname = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string DeleteFlag
        {
            get { return _deleteflag; }
            set
            {

                _isChanged |= (_deleteflag != value); _deleteflag = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime Birthday
        {
            get { return _birthday; }
            set { _isChanged |= (_birthday != value); _birthday = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public bool Blood
        {
            get { return _blood; }
            set { _isChanged |= (_blood != value); _blood = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime OrderTime
        {
            get { return _orderTime; }
            set { _isChanged |= (_orderTime != value); _orderTime = value; }
        }


        public string SampleRemarkName
        {
            get { return _sampleRemarkName; }
            set
            {

                _isChanged |= (_sampleRemarkName != value); _sampleRemarkName = value;
            }
        }

        public string SampleRemarkid
        {
            get { return _sampleRemarkid; }
            set
            {

                _isChanged |= (_sampleRemarkid != value); _sampleRemarkid = value;
            }
        }
        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
        {
            get { return _isChanged; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsDeleted
        {
            get { return _isDeleted; }
        }



        public string BcAppId
        {
            get { return _bcAppId; }
            set
            {

                _isChanged |= (_bcAppId != value); _bcAppId = value;
            }
        }

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public void MarkAsDeleted()
        {
            _isDeleted = true;
            _isChanged = true;
        }

        #endregion


    }
}
